"""Remove user functionality for simplicity

Revision ID: 7a0f72617020
Revises: be5ffb19efdd
Create Date: 2024-11-18 04:40:27.025945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a0f72617020'
down_revision: Union[str, None] = 'be5ffb19efdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_constraint('clothingitem_user_id_fkey', 'clothingitem', type_='foreignkey')
    op.drop_column('clothingitem', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothingitem', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('clothingitem_user_id_fkey', 'clothingitem', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    # ### end Alembic commands ###