"""Add base tables

Revision ID: 94572f7a47c9
Revises: 
Create Date: 2024-11-18 05:02:06.354841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94572f7a47c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WAITING_FOR_FILE', 'PROCESSING', 'FINISHED', 'FAILED', name='clothingitemstatus').create(op.get_bind())
    sa.Enum('FORMAL', 'CASUAL', 'SPORTS', 'NIGHT_OUT', 'OTHER', name='looktype').create(op.get_bind())
    op.create_table('clothingitem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('garment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patterns', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('look_type', postgresql.ENUM('FORMAL', 'CASUAL', 'SPORTS', 'NIGHT_OUT', 'OTHER', name='looktype', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('WAITING_FOR_FILE', 'PROCESSING', 'FINISHED', 'FAILED', name='clothingitemstatus', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothingitem')
    sa.Enum('FORMAL', 'CASUAL', 'SPORTS', 'NIGHT_OUT', 'OTHER', name='looktype').drop(op.get_bind())
    sa.Enum('WAITING_FOR_FILE', 'PROCESSING', 'FINISHED', 'FAILED', name='clothingitemstatus').drop(op.get_bind())
    # ### end Alembic commands ###