"""Add look type

Revision ID: be5ffb19efdd
Revises: e1c526a6665a
Create Date: 2024-11-18 04:11:09.798378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be5ffb19efdd"
down_revision: Union[str, None] = "e1c526a6665a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("FORMAL", "CASUAL", "SPORTS", "NIGHT_OUT", "OTHER", name="looktype").create(
        op.get_bind()
    )
    op.add_column(
        "clothingitem",
        sa.Column(
            "look_type",
            postgresql.ENUM(
                "FORMAL",
                "CASUAL",
                "SPORTS",
                "NIGHT_OUT",
                "OTHER",
                name="looktype",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clothingitem", "look_type")
    sa.Enum("FORMAL", "CASUAL", "SPORTS", "NIGHT_OUT", "OTHER", name="looktype").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
