/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/clothes/": {
    /** Get Clothes */
    get: operations["get_clothes_clothes__get"];
    /** Upload Clothes */
    post: operations["upload_clothes_clothes__post"];
  };
  "/clothes/in-progress": {
    /** Get In Progress Clothes */
    get: operations["get_in_progress_clothes_clothes_in_progress_get"];
  };
  "/uploads/{filename}": {
    /** Get Upload */
    get: operations["get_upload_uploads__filename__get"];
  };
  "/fashiongpt/execute": {
    /** Execute */
    post: operations["execute_fashiongpt_execute_post"];
  };
  "/fashiongpt/suggest": {
    /** Suggest */
    post: operations["suggest_fashiongpt_suggest_post"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Clothes */
    Clothes: {
      /** Clothes */
      clothes: components["schemas"]["ClothingInfo"][];
    };
    /** ClothesInProgress */
    ClothesInProgress: {
      /** Clothes */
      clothes: components["schemas"]["ClothingInfoMinimal"][];
    };
    /** ClothingInfo */
    ClothingInfo: {
      /** Id */
      id: string;
      /** Image */
      image: string;
      status: components["schemas"]["ClothingItemStatus"];
      /** Color */
      color?: string | null;
      /** Garmenttype */
      garmentType?: string | null;
      /** Patterns */
      patterns?: string | null;
      lookType?: components["schemas"]["LookType"] | null;
    };
    /** ClothingInfoMinimal */
    ClothingInfoMinimal: {
      /** Id */
      id: string;
      /** Image */
      image: string;
      status: components["schemas"]["ClothingItemStatus"];
    };
    /**
     * ClothingItemStatus
     * @enum {string}
     */
    ClothingItemStatus: "PROCESSING" | "FINISHED" | "FAILED";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LookType
     * @enum {string}
     */
    LookType: "FORMAL" | "CASUAL" | "SPORTS" | "NIGHT_OUT" | "OTHER";
    /** SuggestionRequest */
    SuggestionRequest: {
      /** Prompt */
      prompt: string;
    };
    /** SuggestionResponse */
    SuggestionResponse: {
      /** Suggestion */
      suggestion: string;
    };
    /** UploadClothRequest */
    UploadClothRequest: {
      /** Imagename */
      imageName: string;
      /** Imagebuffer */
      imageBuffer: string;
    };
    /** UploadClothResponse */
    UploadClothResponse: {
      /** Id */
      id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Clothes */
  get_clothes_clothes__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Clothes"];
        };
      };
    };
  };
  /** Upload Clothes */
  upload_clothes_clothes__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadClothRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UploadClothResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get In Progress Clothes */
  get_in_progress_clothes_clothes_in_progress_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClothesInProgress"];
        };
      };
    };
  };
  /** Get Upload */
  get_upload_uploads__filename__get: {
    parameters: {
      path: {
        filename: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Execute */
  execute_fashiongpt_execute_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Suggest */
  suggest_fashiongpt_suggest_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SuggestionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuggestionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
